openapi: '3.0.2'
info:
  title: Shorty API
  description: |-
    Im Rahmen der zweiten Projektphase der DevOps-Weiterbildung 'aws2302' 
    erstellter URL-Shortening-Service.
  version: '1.0'
servers:
  - url: https://localhost:8080/
paths:
  /:
    post:
      summary: Shortens an URL
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                longUrl:
                  type: string
                user: 
                  type: string
      responses:
        '201':
          description: Short-Url erstellt
          content: 
            application/json:
              schema:
                type: object
                properties:
                  longUrl: 
                    type: string
                  shortUrl:
                    type: string
        '400':
          description: Ungültige Url übergeben
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /{shortUrl}:
    get:
      summary: Gets the long URL for the short one
      parameters:
        - name: shortUrl
          in: path
          required: true
          description: the short Url
          schema:
            type: string
      responses:
        '200':
          description: SHort-Url gefunden, Long-Url wird zurückgegeben
          content:
            application/json:
              schema:
                type: object
                properties:
                    longUrl:
                      type: string
                    shortUrl:
                      type: string
  
  /api/stats/{shortUrl}/:
    post:
      summary: Statistik für Kurz-URL abrufen
      requestBody:
        required: true
        description: Passwort für die Kurz-URL
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
      parameters:
        - name: shortUrl
          in: path
          required: true
          description: Short-Url, für welche die Statistiken abgerufen werden soll
          schema:
            type: string
      responses:
        '200':
          description: Statistiken für die Kurz-URL
          content:
            application/json:
              schema:
                type: object
                properties:
                  longURL:
                    type: string
                  shortURL:
                    type: string
                  clicks:
                    type: number
                  lastClick:
                    type: number
                  createDate:
                    type: number
                  expireDate:
                    type: number
                  OS:
                    type: object
                    properties:
                      Windows:
                        type: number
                      Linux:
                        type: number
                      MacOs:
                        type: number
                  Browser:
                    type: object
                    properties:
                      Chrome:
                        type: number
                      Edge:
                        type: number
                      Firefox:
                        type: number
                      Opera:
                        type: number
                      Safari:
                        type: number
                      Sonstige:
                        type: number
        '401':
          description: Anmeldung fehlgeschlagen, Kurz-Link und/oder Passwort stimmen nicht
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
